"""NumPy backprop training, followed by fixed-point export; toy corpus only."""
import os
os.environ.setdefault('OPENBLAS_NUM_THREADS','1')
import json
import numpy as np
from model import ROOT,D,F,T,S,W,generate

def main():
    PAIRS=json.loads((ROOT/'corpus.json').read_text())
    assert PAIRS and all(isinstance(p,str) and isinstance(a,str) and p and a and len(p+a)+2<=T for p,a in PAIRS)
    rng=np.random.default_rng(11)
    vocab=['<eos>','<bos>','<unk>']+sorted(set(''.join(p+a for p,a in PAIRS)))
    V=len(vocab);lookup={c:i for i,c in enumerate(vocab)}
    inp=np.zeros((len(PAIRS),T),dtype=int);target=inp.copy();mask=np.zeros(inp.shape)
    for b,(p,a) in enumerate(PAIRS):
        seq=[1]+[lookup[c] for c in p+a]+[0]
        inp[b,:len(seq)-1]=seq[:-1];target[b,:len(seq)-1]=seq[1:]
        # Train answer continuation only, never count memorized prompts as accuracy.
        mask[b,len(p):len(seq)-1]=1
    P={'emb':rng.normal(0,.3,(V,D)),'pos':rng.normal(0,.08,(T,D))}
    for name,shape in [('q',(D,D)),('k',(D,D)),('v',(D,D)),('o',(D,D)),
                       ('up',(F,D)),('down',(D,F)),('head',(V,D))]:
        P[name]=rng.normal(0,.15,shape)
    adam1={k:np.zeros_like(v) for k,v in P.items()};adam2={k:v.copy() for k,v in adam1.items()}
    causal=np.triu(np.ones((T,T),dtype=bool),1)
    def norm(x):
        inv=1/np.sqrt(np.mean(x*x,axis=-1,keepdims=True)+1e-5)
        return x*inv,inv
    def backward_norm(g,x,inv):
        return g*inv-x*(inv**3)*np.mean(g*x,axis=-1,keepdims=True)
    best=None
    for step in range(1,4001):
        x=P['emb'][inp]+P['pos'];z,inv0=norm(x)
        qs=z@P['q'].T;ks=z@P['k'].T;vs=z@P['v'].T
        q=np.clip(qs,-3.96875,3.96875);k=np.clip(ks,-3.96875,3.96875);v=np.clip(vs,-3.96875,3.96875)
        dots=q@k.transpose(0,2,1)/8;dots[:,causal]=-1e9
        a=np.exp(dots-dots.max(-1,keepdims=True));a/=a.sum(-1,keepdims=True)
        ctx=a@v;y=x+ctx@P['o'].T;zn,inv1=norm(y)
        hp=zn@P['up'].T;h=np.clip(hp,0,3.96875);r=y+h@P['down'].T
        end,inv2=norm(r);logits=end@P['head'].T
        prob=np.exp(logits-logits.max(-1,keepdims=True));prob/=prob.sum(-1,keepdims=True)
        loss=-np.sum(np.log(prob[np.arange(len(PAIRS))[:,None],np.arange(T),target]+1e-12)*mask)/mask.sum()
        g=prob.copy();g[np.arange(len(PAIRS))[:,None],np.arange(T),target]-=1;g*=mask[:,:,None]/mask.sum()
        G={}
        def gradmat(g,x):return g.reshape(-1,g.shape[-1]).T@x.reshape(-1,x.shape[-1])
        G['head']=gradmat(g,end);gr=backward_norm(g@P['head'],r,inv2)
        G['down']=gradmat(gr,h);gh=(gr@P['down'])*((hp>0)&(hp<3.96875))
        G['up']=gradmat(gh,zn);gy=gr+backward_norm(gh@P['up'],y,inv1)
        G['o']=gradmat(gy,ctx);gc=gy@P['o']
        ga=gc@v.transpose(0,2,1);gv=a.transpose(0,2,1)@gc
        gd=a*(ga-(ga*a).sum(-1,keepdims=True))/8
        gq=(gd@k)*((qs>-3.96875)&(qs<3.96875))
        gk=(gd.transpose(0,2,1)@q)*((ks>-3.96875)&(ks<3.96875))
        gv*=((vs>-3.96875)&(vs<3.96875))
        for name,gg in [('q',gq),('k',gk),('v',gv)]:G[name]=gradmat(gg,z)
        gx=gy+backward_norm(gq@P['q']+gk@P['k']+gv@P['v'],x,inv0)
        G['pos']=gx.sum(0);G['emb']=np.zeros_like(P['emb']);np.add.at(G['emb'],inp,gx)
        for name in P:
            gg=np.clip(G[name],-1,1)
            adam1[name]=.9*adam1[name]+.1*gg;adam2[name]=.999*adam2[name]+.001*gg*gg
            P[name]-=.006*(adam1[name]/(1-.9**step))/(np.sqrt(adam2[name]/(1-.999**step))+1e-8)
        if step%200==0:
            model={'vocab':vocab,'shape':{'d':D,'ff':F,'context':T,'layers':1,'heads':1},
                   'exp_lut':np.rint(np.exp(-np.arange(1025)/64)*32768).astype(int).tolist()}
            for name,value in P.items():
                model[name]=np.clip(np.rint(value*(S if name in ['emb','pos'] else W)),
                                    -32768 if name in ['emb','pos'] else -128,
                                    32767 if name in ['emb','pos'] else 127).astype(int).tolist()
            answers=[generate(p,model)['text'] for p,_ in PAIRS]
            correct=sum(got==want for got,(_,want) in zip(answers,PAIRS))
            print(step,round(float(loss),6),correct,answers,flush=True)
            if best is None or correct>best[0] or (correct==best[0] and loss<best[1]):best=(correct,float(loss),step,model)
            if correct==len(PAIRS) and loss<.005:break
    correct,loss,step,model=best
    (ROOT/'weights.json').write_text(json.dumps(model,ensure_ascii=False)+'\n')
    header=['// Generated by train.py; integers only.',f'#define DIM {D}',f'#define FF {F}',
            '#define CONTEXT 32',f'#define VOCAB {V}']
    image=bytearray();layout={}
    for name in ['emb','pos','q','k','v','o','up','down','head','exp_lut']:
        vals=np.array(model[name]).flatten();typ='int16_t' if name in ['emb','pos'] else ('uint16_t' if name=='exp_lut' else 'int8_t')
        if name=='exp_lut':
            header.append(f'static const {typ} wt_{name}[{len(vals)}] = {{'+','.join(map(str,vals))+'};')
        else:
            while len(image)%4:image.append(0)
            layout[name]={'offset':len(image),'shape':list(np.array(model[name]).shape),'bytes':len(vals)*(2 if typ=='int16_t' else 1)}
            header.append(f'#define wt_{name} ((const {typ} *)(uintptr_t)0x{0x01000000+len(image):08x}u)')
            image.extend(vals.astype('<i2' if typ=='int16_t' else 'i1').tobytes())
    header.append('static const char *const vocabulary[VOCAB] = {'+','.join(json.dumps(c,ensure_ascii=False) for c in vocab)+'};')
    header.append('static const uint32_t codepoints[VOCAB] = {0,0,0,'+','.join(str(ord(c)) for c in vocab[3:])+'};')
    (ROOT/'external.bin').write_bytes(image)
    padded=image+bytes((-len(image))%4)
    (ROOT/'external.hex').write_text(''.join(f'{int.from_bytes(padded[i:i+4], 'little'):08x}\n' for i in range(0,len(padded),4)))
    (ROOT/'layout.json').write_text(json.dumps(layout,indent=2)+'\n')
    (ROOT/'weights.h').write_text('\n'.join(header)+'\n')
    report={'seed':11,'steps':step,'loss':loss,'parameters':sum(v.size for v in P.values()),
            'vocab_size':V,'training_pairs':len(PAIRS),'memorized_exact':correct,
            'scope':'Toy training-set reconstruction only; no held-out language capability claim.',
            'examples':[{'prompt':p,'expected':a,'generated':generate(p,model)['text']} for p,a in PAIRS]}
    (ROOT/'training_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps(report,ensure_ascii=False))

if __name__=='__main__':main()
