#!/usr/bin/env python3
"""Deterministic NumPy training; validation calibrates rejection, test is report-only."""
import os
os.environ.setdefault('OPENBLAS_NUM_THREADS', '1')
import json
import hashlib
import numpy as np
from model_common import ROOT, features, codepoints, samples, infer

def main():
    dataset_path = ROOT / 'model/dataset.json'
    ds = json.loads(dataset_path.read_text())
    splits = {k: samples(ds, k) for k in ['train', 'validation', 'test']}
    # Enforce disjoint normalized examples as well as literal strings.
    sets = [set(tuple(codepoints(t)) for t, _ in splits[k]) for k in splits]
    assert all(not sets[i] & sets[j] for i in range(3) for j in range(i+1, 3)), 'dataset leakage'
    x = np.array([features(t) for t, _ in splits['train']], dtype=np.float64)
    y = np.array([y for _, y in splits['train']])
    rng = np.random.default_rng(7)
    w1 = rng.normal(0, .09, (32, 256)); b1 = np.full(32, .04)
    w2 = rng.normal(0, .1, (6, 32)); b2 = np.zeros(6)
    params = [w1, b1, w2, b2]
    first = [np.zeros_like(p) for p in params]; second = [p.copy() for p in first]
    for step in range(1, 1801):
        pre = x @ w1.T + b1
        h = np.clip(pre, 0, 3.8)
        logits = h @ w2.T + b2
        prob = np.exp(logits - logits.max(axis=1, keepdims=True)); prob /= prob.sum(axis=1, keepdims=True)
        prob[np.arange(len(y)), y] -= 1; prob /= len(y)
        dh = (prob @ w2) * ((pre > 0) & (pre < 3.8))
        grads = [dh.T @ x + .001*w1, dh.sum(axis=0), prob.T @ h + .001*w2, prob.sum(axis=0)]
        for i, (p, g) in enumerate(zip(params, grads)):
            first[i] = .9*first[i] + .1*g; second[i] = .999*second[i] + .001*g*g
            p -= .008*(first[i]/(1-.9**step))/(np.sqrt(second[i]/(1-.999**step))+1e-8)
    quant = lambda a, scale: np.clip(np.rint(a*scale), -128, 127).astype(int).tolist()
    model = {'format_version': 1, 'labels': ds['labels'], 'shape': [256, 32, 6],
             'weight_scale': 32, 'hidden_clip': 127,
             'w1': quant(w1, 32), 'b1': np.rint(b1*32).astype(int).tolist(),
             'w2': quant(w2, 32), 'b2': np.rint(b2*1024).astype(int).tolist(),
             'known_codepoints': sorted(set(c for t, _ in splits['train'] for c in codepoints(t))),
             'known_percent': 0, 'margin_threshold': 0, 'seed': 7}
    best = None
    for known in [30, 40, 50, 60, 70]:
        for margin in [0, 256, 512, 768, 1024, 1536, 2048]:
            model.update(known_percent=known, margin_threshold=margin)
            correct = sum((r := infer(t, model))['accepted'] and r['intent']==label for t,label in splits['validation'])/len(splits['validation'])
            rejected = sum(not infer(t, model)['accepted'] for t in ds['ood_calibration'])/len(ds['ood_calibration'])
            score = correct + rejected
            if best is None or score > best[0]: best = (score, known, margin)
    model.update(known_percent=best[1], margin_threshold=best[2])
    (ROOT/'model/weights.json').write_text(json.dumps(model, ensure_ascii=False, separators=(',', ':'))+'\n')
    def emit(name, vals, typ):
        flat = np.array(vals).flatten().tolist()
        return 'static const '+typ+' '+name+'['+str(len(flat))+'] __attribute__((aligned(4))) = {\n'+',\n'.join(','.join(str(v) for v in flat[i:i+32]) for i in range(0,len(flat),32))+'\n};\n'
    header = '// Generated by scripts/train.py; do not edit.\n'
    for name in ['w1','w2','b1','b2','known_codepoints']:
        header += emit(name, model[name], 'int8_t' if name.startswith('w') else ('uint32_t' if name=='known_codepoints' else 'int32_t'))
    header += f"#define KNOWN_PERCENT {model['known_percent']}\n#define MARGIN_THRESHOLD {model['margin_threshold']}\n"
    (ROOT/'firmware/model_weights.h').write_text(header)
    report = {'seed': 7, 'dataset_sha256': hashlib.sha256(dataset_path.read_bytes()).hexdigest(),
              'weight_bytes': 8384, 'bias_bytes': 152, 'validation_selected_rejection': {'known_percent': best[1], 'margin': best[2]},
              'scope': 'Small manually authored intent corpus, not a general Chinese benchmark.'}
    for split, rows in splits.items():
        xf = np.array([features(t) for t,_ in rows]); yf = np.array([y for _,y in rows])
        float_pred = np.argmax(np.clip(xf @ w1.T+b1,0,3.8) @ w2.T+b2,axis=1)
        rs = [infer(t,model) for t,_ in rows]
        report[split] = {'count':len(rows), 'float_correct':int(np.sum(float_pred==yf)),
                         'int8_correct':sum(r['intent']==y for r,(_,y) in zip(rs,rows)),
                         'accepted_correct':sum(r['accepted'] and r['intent']==y for r,(_,y) in zip(rs,rows)),
                         'cases':[{'text':t,'expected':int(y),'predicted':r['intent'],'accepted':r['accepted'],'margin':r['margin']} for (t,y),r in zip(rows,rs)]}
    report['ood_test'] = {'count':len(ds['ood_test']), 'rejected':sum(not infer(t,model)['accepted'] for t in ds['ood_test']),
                           'cases':[{'text':t,**{k:v for k,v in infer(t,model).items() if k in ['intent','accepted','margin']}} for t in ds['ood_test']]}
    (ROOT/'model/training_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps({k:v for k,v in report.items() if k not in splits and k!='ood_test'},ensure_ascii=False))
    for k in splits: print(k,{a:b for a,b in report[k].items() if a!='cases'})
    print('ood_test', report['ood_test']['rejected'], '/', report['ood_test']['count'])

if __name__=='__main__': main()
